public enum TaskTypes
{
	SubmitScan = 0,
	PrimeShields = 1,
	FuelEngines = 2,
	ChartCourse = 3,
	StartReactor = 4,
	SwipeCard = 5,
	ClearAsteroids = 6,
	UploadData = 7,
	InspectSample = 8,
	EmptyChute = 9,
	EmptyGarbage = 10,
	AlignEngineOutput = 11,
	FixWiring = 12,
	CalibrateDistributor = 13,
	DivertPower = 14,
	UnlockManifolds = 15,
	ResetReactor = 16,
	FixLights = 17,
	CleanO2Filter = 18,
	FixComms = 19,
	RestoreOxy = 20,
	StabilizeSteering = 21
}
